# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 22 14:05:42 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 602)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qts_label = QtGui.QLabel(self.tab)
        self.qts_label.setObjectName("qts_label")
        self.verticalLayout.addWidget(self.qts_label)
        self.qms_label = QtGui.QLabel(self.tab)
        self.qms_label.setObjectName("qms_label")
        self.verticalLayout.addWidget(self.qms_label)
        self.qes_label = QtGui.QLabel(self.tab)
        self.qes_label.setObjectName("qes_label")
        self.verticalLayout.addWidget(self.qes_label)
        self.vas_label = QtGui.QLabel(self.tab)
        self.vas_label.setObjectName("vas_label")
        self.verticalLayout.addWidget(self.vas_label)
        self.fs_label = QtGui.QLabel(self.tab)
        self.fs_label.setObjectName("fs_label")
        self.verticalLayout.addWidget(self.fs_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.line_5 = QtGui.QFrame(self.tab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.info_groupbox = QtGui.QGroupBox(self.tab)
        self.info_groupbox.setObjectName("info_groupbox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.info_groupbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.qts_info_label = QtGui.QLabel(self.info_groupbox)
        self.qts_info_label.setObjectName("qts_info_label")
        self.verticalLayout_8.addWidget(self.qts_info_label)
        self.qms_info_label = QtGui.QLabel(self.info_groupbox)
        self.qms_info_label.setObjectName("qms_info_label")
        self.verticalLayout_8.addWidget(self.qms_info_label)
        self.qes_info_label = QtGui.QLabel(self.info_groupbox)
        self.qes_info_label.setObjectName("qes_info_label")
        self.verticalLayout_8.addWidget(self.qes_info_label)
        self.vas_info_label = QtGui.QLabel(self.info_groupbox)
        self.vas_info_label.setObjectName("vas_info_label")
        self.verticalLayout_8.addWidget(self.vas_info_label)
        self.fs_info_label = QtGui.QLabel(self.info_groupbox)
        self.fs_info_label.setObjectName("fs_info_label")
        self.verticalLayout_8.addWidget(self.fs_info_label)
        self.verticalLayout_7.addWidget(self.info_groupbox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        spacerItem1 = QtGui.QSpacerItem(20, 407, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        spacerItem2 = QtGui.QSpacerItem(20, 407, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.cancel_button = QtGui.QPushButton(self.centralWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.ok_button = QtGui.QPushButton(self.centralWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 751, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.qts_label.setText(QtGui.QApplication.translate("MainWindow", "Qts:", None, QtGui.QApplication.UnicodeUTF8))
        self.qms_label.setText(QtGui.QApplication.translate("MainWindow", "Qms:", None, QtGui.QApplication.UnicodeUTF8))
        self.qes_label.setText(QtGui.QApplication.translate("MainWindow", "Qes:", None, QtGui.QApplication.UnicodeUTF8))
        self.vas_label.setText(QtGui.QApplication.translate("MainWindow", "Vas:", None, QtGui.QApplication.UnicodeUTF8))
        self.fs_label.setText(QtGui.QApplication.translate("MainWindow", "Fs:", None, QtGui.QApplication.UnicodeUTF8))
        self.info_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.qts_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qts: Total Q of the driver at Fs.", None, QtGui.QApplication.UnicodeUTF8))
        self.qms_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qms: Mechanical Q of the driver at Fs.", None, QtGui.QApplication.UnicodeUTF8))
        self.qes_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qes: Electrical Q of the driver at Fs", None, QtGui.QApplication.UnicodeUTF8))
        self.vas_info_label.setText(QtGui.QApplication.translate("MainWindow", "Vas: Equivalent Compliance Volume in litres.", None, QtGui.QApplication.UnicodeUTF8))
        self.fs_info_label.setText(QtGui.QApplication.translate("MainWindow", "Fs: Resonant frequency of the driver in hertz.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Small signal params", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Fundamental mechanical params", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Large signal params", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_button.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))

