# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 22 15:43:15 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 602)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.qts_label = QtGui.QLabel(self.tab)
        self.qts_label.setObjectName("qts_label")
        self.verticalLayout.addWidget(self.qts_label)
        self.qms_label = QtGui.QLabel(self.tab)
        self.qms_label.setObjectName("qms_label")
        self.verticalLayout.addWidget(self.qms_label)
        self.qes_label = QtGui.QLabel(self.tab)
        self.qes_label.setObjectName("qes_label")
        self.verticalLayout.addWidget(self.qes_label)
        self.vas_label = QtGui.QLabel(self.tab)
        self.vas_label.setObjectName("vas_label")
        self.verticalLayout.addWidget(self.vas_label)
        self.fs_label = QtGui.QLabel(self.tab)
        self.fs_label.setObjectName("fs_label")
        self.verticalLayout.addWidget(self.fs_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.tab)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.line_5 = QtGui.QFrame(self.tab)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.info_groupbox = QtGui.QGroupBox(self.tab)
        self.info_groupbox.setObjectName("info_groupbox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.info_groupbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.qts_info_label = QtGui.QLabel(self.info_groupbox)
        self.qts_info_label.setObjectName("qts_info_label")
        self.verticalLayout_8.addWidget(self.qts_info_label)
        self.qms_info_label = QtGui.QLabel(self.info_groupbox)
        self.qms_info_label.setObjectName("qms_info_label")
        self.verticalLayout_8.addWidget(self.qms_info_label)
        self.qes_info_label = QtGui.QLabel(self.info_groupbox)
        self.qes_info_label.setObjectName("qes_info_label")
        self.verticalLayout_8.addWidget(self.qes_info_label)
        self.vas_info_label = QtGui.QLabel(self.info_groupbox)
        self.vas_info_label.setObjectName("vas_info_label")
        self.verticalLayout_8.addWidget(self.vas_info_label)
        self.fs_info_label = QtGui.QLabel(self.info_groupbox)
        self.fs_info_label.setObjectName("fs_info_label")
        self.verticalLayout_8.addWidget(self.fs_info_label)
        self.verticalLayout_7.addWidget(self.info_groupbox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_10.addWidget(self.line_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sd_label = QtGui.QLabel(self.tab_2)
        self.sd_label.setObjectName("sd_label")
        self.verticalLayout_2.addWidget(self.sd_label)
        self.mms_label = QtGui.QLabel(self.tab_2)
        self.mms_label.setObjectName("mms_label")
        self.verticalLayout_2.addWidget(self.mms_label)
        self.cms_label = QtGui.QLabel(self.tab_2)
        self.cms_label.setObjectName("cms_label")
        self.verticalLayout_2.addWidget(self.cms_label)
        self.rms_label = QtGui.QLabel(self.tab_2)
        self.rms_label.setObjectName("rms_label")
        self.verticalLayout_2.addWidget(self.rms_label)
        self.le_label = QtGui.QLabel(self.tab_2)
        self.le_label.setObjectName("le_label")
        self.verticalLayout_2.addWidget(self.le_label)
        self.re_label = QtGui.QLabel(self.tab_2)
        self.re_label.setObjectName("re_label")
        self.verticalLayout_2.addWidget(self.re_label)
        self.bl_label = QtGui.QLabel(self.tab_2)
        self.bl_label.setObjectName("bl_label")
        self.verticalLayout_2.addWidget(self.bl_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sd_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.sd_lineEdit.setObjectName("sd_lineEdit")
        self.verticalLayout_9.addWidget(self.sd_lineEdit)
        self.mms_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.mms_lineEdit.setObjectName("mms_lineEdit")
        self.verticalLayout_9.addWidget(self.mms_lineEdit)
        self.cms_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.cms_lineEdit.setObjectName("cms_lineEdit")
        self.verticalLayout_9.addWidget(self.cms_lineEdit)
        self.rms_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.rms_lineEdit.setObjectName("rms_lineEdit")
        self.verticalLayout_9.addWidget(self.rms_lineEdit)
        self.le_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.le_lineEdit.setObjectName("le_lineEdit")
        self.verticalLayout_9.addWidget(self.le_lineEdit)
        self.re_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.re_lineEdit.setObjectName("re_lineEdit")
        self.verticalLayout_9.addWidget(self.re_lineEdit)
        self.bl_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.bl_lineEdit.setObjectName("bl_lineEdit")
        self.verticalLayout_9.addWidget(self.bl_lineEdit)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.sd_info_label = QtGui.QLabel(self.groupBox)
        self.sd_info_label.setObjectName("sd_info_label")
        self.verticalLayout_11.addWidget(self.sd_info_label)
        self.mms_info_label = QtGui.QLabel(self.groupBox)
        self.mms_info_label.setObjectName("mms_info_label")
        self.verticalLayout_11.addWidget(self.mms_info_label)
        self.cms_info_label = QtGui.QLabel(self.groupBox)
        self.cms_info_label.setObjectName("cms_info_label")
        self.verticalLayout_11.addWidget(self.cms_info_label)
        self.rms_info_label = QtGui.QLabel(self.groupBox)
        self.rms_info_label.setObjectName("rms_info_label")
        self.verticalLayout_11.addWidget(self.rms_info_label)
        self.le_info_label = QtGui.QLabel(self.groupBox)
        self.le_info_label.setObjectName("le_info_label")
        self.verticalLayout_11.addWidget(self.le_info_label)
        self.re_info_label = QtGui.QLabel(self.groupBox)
        self.re_info_label.setObjectName("re_info_label")
        self.verticalLayout_11.addWidget(self.re_info_label)
        self.bl_info_label = QtGui.QLabel(self.groupBox)
        self.bl_info_label.setObjectName("bl_info_label")
        self.verticalLayout_11.addWidget(self.bl_info_label)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        spacerItem = QtGui.QSpacerItem(20, 426, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_4 = QtGui.QFrame(self.tab_4)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_4.addWidget(self.line_4)
        spacerItem1 = QtGui.QSpacerItem(20, 426, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cancel_button = QtGui.QPushButton(self.centralWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.ok_button = QtGui.QPushButton(self.centralWidget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 751, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.qts_label.setText(QtGui.QApplication.translate("MainWindow", "Qts:", None, QtGui.QApplication.UnicodeUTF8))
        self.qms_label.setText(QtGui.QApplication.translate("MainWindow", "Qms:", None, QtGui.QApplication.UnicodeUTF8))
        self.qes_label.setText(QtGui.QApplication.translate("MainWindow", "Qes:", None, QtGui.QApplication.UnicodeUTF8))
        self.vas_label.setText(QtGui.QApplication.translate("MainWindow", "Vas:", None, QtGui.QApplication.UnicodeUTF8))
        self.fs_label.setText(QtGui.QApplication.translate("MainWindow", "Fs:", None, QtGui.QApplication.UnicodeUTF8))
        self.info_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.qts_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qts: Total Q of the driver at Fs.", None, QtGui.QApplication.UnicodeUTF8))
        self.qms_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qms: Mechanical Q of the driver at Fs.", None, QtGui.QApplication.UnicodeUTF8))
        self.qes_info_label.setText(QtGui.QApplication.translate("MainWindow", "Qes: Electrical Q of the driver at Fs", None, QtGui.QApplication.UnicodeUTF8))
        self.vas_info_label.setText(QtGui.QApplication.translate("MainWindow", "Vas: Equivalent Compliance Volume in litres.", None, QtGui.QApplication.UnicodeUTF8))
        self.fs_info_label.setText(QtGui.QApplication.translate("MainWindow", "Fs: Resonant frequency of the driver in hertz.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Small signal params", None, QtGui.QApplication.UnicodeUTF8))
        self.sd_label.setText(QtGui.QApplication.translate("MainWindow", "Sd:", None, QtGui.QApplication.UnicodeUTF8))
        self.mms_label.setText(QtGui.QApplication.translate("MainWindow", "Mms:", None, QtGui.QApplication.UnicodeUTF8))
        self.cms_label.setText(QtGui.QApplication.translate("MainWindow", "Cms:", None, QtGui.QApplication.UnicodeUTF8))
        self.rms_label.setText(QtGui.QApplication.translate("MainWindow", "Rms:", None, QtGui.QApplication.UnicodeUTF8))
        self.le_label.setText(QtGui.QApplication.translate("MainWindow", "Le:", None, QtGui.QApplication.UnicodeUTF8))
        self.re_label.setText(QtGui.QApplication.translate("MainWindow", "Re:", None, QtGui.QApplication.UnicodeUTF8))
        self.bl_label.setText(QtGui.QApplication.translate("MainWindow", "Bl:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.sd_info_label.setText(QtGui.QApplication.translate("MainWindow", "Sd: Projected area of the driver diaphragm, in square metres.", None, QtGui.QApplication.UnicodeUTF8))
        self.mms_info_label.setText(QtGui.QApplication.translate("MainWindow", "Mms: Mass of the diaphragm/coil, including acoustic load, in kilograms.", None, QtGui.QApplication.UnicodeUTF8))
        self.cms_info_label.setText(QtGui.QApplication.translate("MainWindow", "Cms: Compliance of the driver\'s suspension, in metres per newton (the reciprocal of its \'stiffness\').", None, QtGui.QApplication.UnicodeUTF8))
        self.rms_info_label.setText(QtGui.QApplication.translate("MainWindow", "Rms: The mechanical resistance of a driver\'s suspension (ie, \'lossiness\') in N*s/m", None, QtGui.QApplication.UnicodeUTF8))
        self.le_info_label.setText(QtGui.QApplication.translate("MainWindow", "Le: Voice coil inductance measured in millihenries (mH) (Frequency dependent)", None, QtGui.QApplication.UnicodeUTF8))
        self.re_info_label.setText(QtGui.QApplication.translate("MainWindow", "Re: DC resistance of the voice coil, measured in ohms.", None, QtGui.QApplication.UnicodeUTF8))
        self.bl_info_label.setText(QtGui.QApplication.translate("MainWindow", "Bl: The product of magnet field strength in the voice coil gap and the length of wire in the magnetic field, in tesla-metres (T*m).", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Fundamental mechanical params", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Large signal params", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_button.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))

